// app/layout.tsx
import type { Metadata } from "next";
import { Noto_Sans_Armenian } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";

const geistSans = Noto_Sans_Armenian({
  variable: "--font-geist-sans",
  subsets: ["armenian"],
});

const geistMono = Noto_Sans_Armenian({
  variable: "--font-geist-mono",
  subsets: ["armenian"],
});

export const metadata: Metadata = {
  title: "ItClub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
