import type { Metadata } from "next";
import { Noto_Sans_Armenian } from "next/font/google";
import Navbar from "@front/components/Navbar";
import Footer from "@front/components/Footer";

const geistSans = Noto_Sans_Armenian({
  variable: "--font-geist-sans",
  subsets: ["armenian"],
});

const geistMono = Noto_Sans_Armenian({
  variable: "--font-geist-mono",
  subsets: ["armenian"],
});

export const metadata: Metadata = {
  title: "ITClub ՏՏ դասընթացներ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        {children}
        {modal}
        <Footer />
      </body>
    </html>
  );
}
