name: CI-CD 
on: 
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'README.md'
    - 'README.rst'
env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  IMAGE_FRONT: lyaralyan/itclub
  IMAGE_FRONT_TAG: ${{ github.sha }}
  # MONGO_HOST: ${{ secrets.MONGO_HOST }}
  # MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone
        uses: actions/checkout@v3
     
      - name: Login to Dockerhub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
     # Build and Push container to DockerHub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_FRONT }}:${{ env.IMAGE_FRONT_TAG }}
        
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Git clone 
        uses: actions/checkout@v3

      - name: Deploy to prod
        env:
            SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
            SERVER_USER: ${{ secrets.SERVER_USER }}
            SERVER_HOST: ${{ secrets.SERVER_HOST }}
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
            # Optional debug step to ensure variables are not empty
            echo "Deploying to $SERVER_USER@$SERVER_HOST"
            echo "Image: $IMAGE_FRONT:$IMAGE_FRONT_TAG"
            echo "$SSH_KEY" | tr -d '\r' > id_rsa
            echo "$SSH_KEY" > id_rsa
            chmod 600 id_rsa
            # Use sshpass with environment variable mode for safety
            ssh -i id_rsa \
              -o StrictHostKeyChecking=no \
              -p 22 "$SERVER_USER@$SERVER_HOST" "\
                docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && \
                docker pull $IMAGE_FRONT:$IMAGE_FRONT_TAG && \
                /home/it-adm/club-dev/docker-confs/image.sh \
              "
# end
