name: CI-CD 
on: 
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'README.md'
    - 'README.rst'
env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  IMAGE_FRONT: lyaralyan/itclub
  IMAGE_FRONT_TAG: ${{ github.sha }}
  MONGO_HOST: ${{ secrets.MONGO_HOST }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone
        uses: actions/checkout@v3
     
      - name: Login to Dockerhub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
     # Build and Push container to DockerHub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_FRONT }}:${{ env.IMAGE_FRONT_TAG }}
        
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Git clone 
        uses: actions/checkout@v3

      - name: Deploy to prod
        run: |
          ssh -o StrictHostKeyChecking=no -p $SERVER_USER@$SERVER_HOST "\
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && \
            docker pull $IMAGE_FRONT:$IMAGE_FRONT_TAG && \
            /home/it-adm/club-dev/docker-confs/image.sh \
          "
